"""01_wallet_and_transaction

Revision ID: 53d06bc95d63
Revises:
Create Date: 2024-10-12 00:24:29.304698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "53d06bc95d63"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wallet",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=128), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("balance", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.CheckConstraint("balance >= 0", name="check_wallet_balance_non_negative"),
        sa.CheckConstraint("length(name) >= 1 AND length(name) <= 128", name="check_wallet_name_length"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("wallet_idx_user_id", "wallet", ["user_id"], unique=False)
    op.create_table(
        "transaction",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sender_wallet_id", sa.UUID(), nullable=False),
        sa.Column("receiver_wallet_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.CheckConstraint("amount >= 0", name="check_transaction_amount_non_negative"),
        sa.ForeignKeyConstraint(
            ["receiver_wallet_id"],
            ["wallet.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sender_wallet_id"],
            ["wallet.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("transaction_idx_user_id", "transaction", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("transaction_idx_user_id", table_name="transaction")
    op.drop_table("transaction")
    op.drop_index("wallet_idx_user_id", table_name="wallet")
    op.drop_table("wallet")
    # ### end Alembic commands ###
