"""02_event_table

Revision ID: 116085f8599a
Revises: 53d06bc95d63
Create Date: 2025-01-02 16:33:59.256710

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "116085f8599a"
down_revision = "53d06bc95d63"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transaction_event",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("status", sa.Enum("NEW", "FAIL", "SUCCESS", name="eventstatus"), nullable=False),
        sa.Column("body", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("transaction_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transaction.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("transaction", sa.Column("event_id", sa.UUID(), nullable=False))
    op.create_foreign_key(None, "transaction", "transaction_event", ["event_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "transaction", type_="foreignkey")
    op.drop_column("transaction", "event_id")
    op.drop_table("transaction_event")
    # ### end Alembic commands ###
